; Generated by AutoGUI 1.4.9a
#NoEnv
#SingleInstance Force

SetWorkingDir %A_ScriptDir%

BaseDir := "D:\MySelf\summoners_war"
BaseDir = %A_ScriptDir%
kairos := BaseDir . "\window\카이로스던전.bmp"

Gui Add, Button, x8 y8 w83 h22, &Start
Gui Add, Edit, x8 y40 w481 h264 Multi +ReadOnly vLogs, 시작
Gui Add, Button, x96 y8 w80 h23, &Stop

Gui Show, w497 h312, 서머너즈워
Return

GuiEscape:
GuiClose:
ExitApp

; Do not edit above this line
global Logs


AddLog(strings)
{	Logs .= strings . "`n"
	GuiControl,, Logs, %Logs%
}

FindScene(scene)
{
	AddLog("FindScene start:" . scene)
	ImageSearch, X, Y, 0, 0, %A_ScreenWidth%, %A_ScreenHeight%, %scene%
	if (ErrorLevel = 0) {		
		AddLog("found!!")
	} else if (ErrorLevel = 1) {
		AddLog("not found the image in the screen")
	} else if (ErrorLevel =2 ) {
		AddLog("not found image file:" . %scene%)
	} else {
		AddLog("unknown errorto find image:" . ErrorLevel)
	}
	
	return
}




ButtonStart:
AddLog("basepath is " . BaseDir)
AddLog("path is " . kairos)

FindScene(kairos)
return


